import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import tutorsRouter from "./tutors";
import sessionsRouter from "./sessions";
import transactionsRouter from "./transactions";
import messagesRouter from "./messages";
import adminRouter from "./admin";
import materialsRouter from "./materials";
import socialRouter from "./social";
import universitiesRouter from "./universities";
import statsRouter from "./stats";
import superadminRouter from "./superadmin";
import sponsorshipRouter from "./sponsorship";
import walletRouter from "./wallet";
import aiRouter from "./ai";
import notificationsRouter from "./notifications";
import reviewsRouter from "./reviews";
import assignmentsRouter from "./assignments";
import leaderboardRouter from "./leaderboard";
import referralsRouter from "./referrals";
import groupsRouter from "./groups";
import adminResetTempRouter from "./admin-reset-temp";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/stats", statsRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/tutors", tutorsRouter);
router.use("/sessions", sessionsRouter);
router.use("/transactions", transactionsRouter);
router.use("/messages", messagesRouter);
router.use("/admin", adminRouter);
router.use("/materials", materialsRouter);
router.use("/social", socialRouter);
router.use("/universities", universitiesRouter);
router.use("/superadmin", superadminRouter);
router.use("/sponsorship-requests", sponsorshipRouter);
router.use("/admin-reset-temp", adminResetTempRouter);
router.use("/wallet", walletRouter);
router.use("/ai", aiRouter);
router.use("/notifications", notificationsRouter);
router.use("/reviews", reviewsRouter);
router.use("/assignments", assignmentsRouter);
router.use("/leaderboard", leaderboardRouter);
router.use("/referrals", referralsRouter);
router.use("/groups", groupsRouter);

export default router;
