export interface CurrencyInfo {
  symbol: string;
  code: string;
  name: string;
}

const COUNTRY_CURRENCY: Record<string, CurrencyInfo> = {
  "Nigeria": { symbol: "₦", code: "NGN", name: "Nigerian Naira" },
  "United States": { symbol: "$", code: "USD", name: "US Dollar" },
  "United Kingdom": { symbol: "£", code: "GBP", name: "British Pound" },
  "Canada": { symbol: "CA$", code: "CAD", name: "Canadian Dollar" },
  "Australia": { symbol: "A$", code: "AUD", name: "Australian Dollar" },
  "New Zealand": { symbol: "NZ$", code: "NZD", name: "New Zealand Dollar" },
  "Germany": { symbol: "€", code: "EUR", name: "Euro" },
  "France": { symbol: "€", code: "EUR", name: "Euro" },
  "Italy": { symbol: "€", code: "EUR", name: "Euro" },
  "Spain": { symbol: "€", code: "EUR", name: "Euro" },
  "Netherlands": { symbol: "€", code: "EUR", name: "Euro" },
  "Belgium": { symbol: "€", code: "EUR", name: "Euro" },
  "Portugal": { symbol: "€", code: "EUR", name: "Euro" },
  "Austria": { symbol: "€", code: "EUR", name: "Euro" },
  "Greece": { symbol: "€", code: "EUR", name: "Euro" },
  "Finland": { symbol: "€", code: "EUR", name: "Euro" },
  "Ireland": { symbol: "€", code: "EUR", name: "Euro" },
  "Luxembourg": { symbol: "€", code: "EUR", name: "Euro" },
  "Malta": { symbol: "€", code: "EUR", name: "Euro" },
  "Cyprus": { symbol: "€", code: "EUR", name: "Euro" },
  "Slovakia": { symbol: "€", code: "EUR", name: "Euro" },
  "Slovenia": { symbol: "€", code: "EUR", name: "Euro" },
  "Estonia": { symbol: "€", code: "EUR", name: "Euro" },
  "Latvia": { symbol: "€", code: "EUR", name: "Euro" },
  "Lithuania": { symbol: "€", code: "EUR", name: "Euro" },
  "Croatia": { symbol: "€", code: "EUR", name: "Euro" },
  "Sweden": { symbol: "kr", code: "SEK", name: "Swedish Krona" },
  "Norway": { symbol: "kr", code: "NOK", name: "Norwegian Krone" },
  "Denmark": { symbol: "kr", code: "DKK", name: "Danish Krone" },
  "Switzerland": { symbol: "CHF", code: "CHF", name: "Swiss Franc" },
  "Japan": { symbol: "¥", code: "JPY", name: "Japanese Yen" },
  "China": { symbol: "¥", code: "CNY", name: "Chinese Yuan" },
  "India": { symbol: "₹", code: "INR", name: "Indian Rupee" },
  "South Korea": { symbol: "₩", code: "KRW", name: "South Korean Won" },
  "Singapore": { symbol: "S$", code: "SGD", name: "Singapore Dollar" },
  "Hong Kong": { symbol: "HK$", code: "HKD", name: "Hong Kong Dollar" },
  "Malaysia": { symbol: "RM", code: "MYR", name: "Malaysian Ringgit" },
  "Thailand": { symbol: "฿", code: "THB", name: "Thai Baht" },
  "Indonesia": { symbol: "Rp", code: "IDR", name: "Indonesian Rupiah" },
  "Philippines": { symbol: "₱", code: "PHP", name: "Philippine Peso" },
  "Vietnam": { symbol: "₫", code: "VND", name: "Vietnamese Dong" },
  "Pakistan": { symbol: "Rs", code: "PKR", name: "Pakistani Rupee" },
  "Bangladesh": { symbol: "৳", code: "BDT", name: "Bangladeshi Taka" },
  "Sri Lanka": { symbol: "Rs", code: "LKR", name: "Sri Lankan Rupee" },
  "Nepal": { symbol: "Rs", code: "NPR", name: "Nepalese Rupee" },
  "Ghana": { symbol: "₵", code: "GHS", name: "Ghanaian Cedi" },
  "South Africa": { symbol: "R", code: "ZAR", name: "South African Rand" },
  "Kenya": { symbol: "KSh", code: "KES", name: "Kenyan Shilling" },
  "Tanzania": { symbol: "TSh", code: "TZS", name: "Tanzanian Shilling" },
  "Uganda": { symbol: "USh", code: "UGX", name: "Ugandan Shilling" },
  "Ethiopia": { symbol: "Br", code: "ETB", name: "Ethiopian Birr" },
  "Egypt": { symbol: "E£", code: "EGP", name: "Egyptian Pound" },
  "Morocco": { symbol: "MAD", code: "MAD", name: "Moroccan Dirham" },
  "Tunisia": { symbol: "DT", code: "TND", name: "Tunisian Dinar" },
  "Algeria": { symbol: "DA", code: "DZD", name: "Algerian Dinar" },
  "Libya": { symbol: "LD", code: "LYD", name: "Libyan Dinar" },
  "Sudan": { symbol: "SDG", code: "SDG", name: "Sudanese Pound" },
  "Cameroon": { symbol: "FCFA", code: "XAF", name: "Central African Franc" },
  "Senegal": { symbol: "FCFA", code: "XOF", name: "West African Franc" },
  "Côte d'Ivoire": { symbol: "FCFA", code: "XOF", name: "West African Franc" },
  "Mali": { symbol: "FCFA", code: "XOF", name: "West African Franc" },
  "Niger": { symbol: "FCFA", code: "XOF", name: "West African Franc" },
  "Burkina Faso": { symbol: "FCFA", code: "XOF", name: "West African Franc" },
  "Benin": { symbol: "FCFA", code: "XOF", name: "West African Franc" },
  "Togo": { symbol: "FCFA", code: "XOF", name: "West African Franc" },
  "Guinea": { symbol: "FG", code: "GNF", name: "Guinean Franc" },
  "Sierra Leone": { symbol: "Le", code: "SLL", name: "Sierra Leonean Leone" },
  "Liberia": { symbol: "L$", code: "LRD", name: "Liberian Dollar" },
  "Gambia": { symbol: "D", code: "GMD", name: "Gambian Dalasi" },
  "Zambia": { symbol: "ZK", code: "ZMW", name: "Zambian Kwacha" },
  "Zimbabwe": { symbol: "Z$", code: "ZWL", name: "Zimbabwean Dollar" },
  "Mozambique": { symbol: "MT", code: "MZN", name: "Mozambican Metical" },
  "Angola": { symbol: "Kz", code: "AOA", name: "Angolan Kwanza" },
  "Namibia": { symbol: "N$", code: "NAD", name: "Namibian Dollar" },
  "Botswana": { symbol: "P", code: "BWP", name: "Botswana Pula" },
  "Rwanda": { symbol: "RF", code: "RWF", name: "Rwandan Franc" },
  "Brazil": { symbol: "R$", code: "BRL", name: "Brazilian Real" },
  "Mexico": { symbol: "$", code: "MXN", name: "Mexican Peso" },
  "Argentina": { symbol: "$", code: "ARS", name: "Argentine Peso" },
  "Colombia": { symbol: "$", code: "COP", name: "Colombian Peso" },
  "Chile": { symbol: "$", code: "CLP", name: "Chilean Peso" },
  "Peru": { symbol: "S/", code: "PEN", name: "Peruvian Sol" },
  "Venezuela": { symbol: "Bs.", code: "VES", name: "Venezuelan Bolívar" },
  "Ecuador": { symbol: "$", code: "USD", name: "US Dollar" },
  "Saudi Arabia": { symbol: "﷼", code: "SAR", name: "Saudi Riyal" },
  "United Arab Emirates": { symbol: "د.إ", code: "AED", name: "UAE Dirham" },
  "Qatar": { symbol: "﷼", code: "QAR", name: "Qatari Riyal" },
  "Kuwait": { symbol: "KD", code: "KWD", name: "Kuwaiti Dinar" },
  "Bahrain": { symbol: "BD", code: "BHD", name: "Bahraini Dinar" },
  "Oman": { symbol: "﷼", code: "OMR", name: "Omani Rial" },
  "Jordan": { symbol: "JD", code: "JOD", name: "Jordanian Dinar" },
  "Israel": { symbol: "₪", code: "ILS", name: "Israeli Shekel" },
  "Turkey": { symbol: "₺", code: "TRY", name: "Turkish Lira" },
  "Russia": { symbol: "₽", code: "RUB", name: "Russian Ruble" },
  "Ukraine": { symbol: "₴", code: "UAH", name: "Ukrainian Hryvnia" },
  "Poland": { symbol: "zł", code: "PLN", name: "Polish Złoty" },
  "Czech Republic": { symbol: "Kč", code: "CZK", name: "Czech Koruna" },
  "Hungary": { symbol: "Ft", code: "HUF", name: "Hungarian Forint" },
  "Romania": { symbol: "lei", code: "RON", name: "Romanian Leu" },
  "Bulgaria": { symbol: "лв", code: "BGN", name: "Bulgarian Lev" },
  "Serbia": { symbol: "din", code: "RSD", name: "Serbian Dinar" },
};

const DEFAULT_CURRENCY: CurrencyInfo = { symbol: "₦", code: "NGN", name: "Nigerian Naira" };

export function getCurrency(country?: string | null): CurrencyInfo {
  if (!country) return DEFAULT_CURRENCY;
  return COUNTRY_CURRENCY[country] ?? DEFAULT_CURRENCY;
}

export function formatAmount(amount: number | string, country?: string | null): string {
  const { symbol } = getCurrency(country);
  const num = Number(amount);
  return `${symbol}${num.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 2 })}`;
}

export const COUNTRIES = [
  "Afghanistan","Albania","Algeria","Andorra","Angola","Antigua and Barbuda","Argentina","Armenia","Australia","Austria",
  "Azerbaijan","Bahamas","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bhutan",
  "Bolivia","Bosnia and Herzegovina","Botswana","Brazil","Brunei","Bulgaria","Burkina Faso","Burundi","Cabo Verde","Cambodia",
  "Cameroon","Canada","Central African Republic","Chad","Chile","China","Colombia","Comoros","Congo (Brazzaville)","Congo (Kinshasa)",
  "Costa Rica","Côte d'Ivoire","Croatia","Cuba","Cyprus","Czech Republic","Denmark","Djibouti","Dominica","Dominican Republic",
  "Ecuador","Egypt","El Salvador","Equatorial Guinea","Eritrea","Estonia","Eswatini","Ethiopia","Fiji","Finland",
  "France","Gabon","Gambia","Georgia","Germany","Ghana","Greece","Grenada","Guatemala","Guinea",
  "Guinea-Bissau","Guyana","Haiti","Honduras","Hungary","Iceland","India","Indonesia","Iran","Iraq",
  "Ireland","Israel","Italy","Jamaica","Japan","Jordan","Kazakhstan","Kenya","Kiribati","Kuwait",
  "Kyrgyzstan","Laos","Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg",
  "Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Marshall Islands","Mauritania","Mauritius","Mexico",
  "Micronesia","Moldova","Monaco","Mongolia","Montenegro","Morocco","Mozambique","Myanmar","Namibia","Nauru",
  "Nepal","Netherlands","New Zealand","Nicaragua","Niger","Nigeria","North Korea","North Macedonia","Norway","Oman",
  "Pakistan","Palau","Palestine","Panama","Papua New Guinea","Paraguay","Peru","Philippines","Poland","Portugal",
  "Qatar","Romania","Russia","Rwanda","Saint Kitts and Nevis","Saint Lucia","Saint Vincent and the Grenadines","Samoa","San Marino","São Tomé and Príncipe",
  "Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Slovakia","Slovenia","Solomon Islands","Somalia",
  "South Africa","South Korea","South Sudan","Spain","Sri Lanka","Sudan","Suriname","Sweden","Switzerland","Syria",
  "Taiwan","Tajikistan","Tanzania","Thailand","Timor-Leste","Togo","Tonga","Trinidad and Tobago","Tunisia","Turkey",
  "Turkmenistan","Tuvalu","Uganda","Ukraine","United Arab Emirates","United Kingdom","United States","Uruguay","Uzbekistan","Vanuatu",
  "Vatican City","Venezuela","Vietnam","Yemen","Zambia","Zimbabwe",
].sort();
